routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register Admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "web", "auth" and "admin" middleware groups. Enjoy building your Admin!
|
*/

/**
 * admin url
 */
Route::get('/', ['uses' => 'AdminController@index', 'as' => 'admin.index']);
Route::get('/settings', ['uses' => 'AdminController@settings', 'as' => 'admin.settings']);
Route::post('/settings', ['uses' => 'AdminController@saveSettings', 'as' => 'admin.save-settings']);
Route::post('/upload/image', ['uses' => 'ImageController@uploadImage', 'as' => 'upload.image']);
Route::delete('/delete/file', ['uses' => 'FileController@deleteFile', 'as' => 'delete.file']);
Route::post('/upload/file', ['uses' => 'FileController@uploadFile', 'as' => 'upload.file']);


/**
 * admin uri
 */
Route::get('/posts', ['uses' => 'AdminController@posts', 'as' => 'admin.posts']);
Route::get('/comments', ['uses' => 'AdminController@comments', 'as' => 'admin.comments']);
Route::get('/tags', ['uses' => 'AdminController@tags', 'as' => 'admin.tags']);
Route::get('/users', ['uses' => 'AdminController@users', 'as' => 'admin.users']);
Route::get('/pages', ['uses' => 'AdminController@pages', 'as' => 'admin.pages']);
Route::get('/categories', ['uses' => 'AdminController@categories', 'as' => 'admin.categories']);
Route::get('/images', ['uses' => 'ImageController@images', 'as' => 'admin.images']);
Route::get('/images-list', ['uses' => 'ImageController@images_list', 'as' => 'admin.images-list']);
Route::get('/files', ['uses' => 'FileController@files', 'as' => 'admin.files']);
Route::get('/ips', ['uses' => 'AdminController@ips', 'as' => 'admin.ips']);
Route::get('/app', ['uses' => 'AppController@index', 'as' => 'admin.app']);
Route::post('/app/email', ['uses' => 'AppController@sendMail', 'as' => 'admin.app.send-mail']);

/**
 * comment
 */
Route::post('/comment/{comment}/restore', ['uses' => 'CommentController@restore', 'as' => 'comment.restore']);
Route::match(['get', 'post'], '/comment/{comment}/verify', ['uses' => 'CommentController@verify', 'as' => 'comment.verify']);
Route::delete('comment/un-verified', ['uses' => 'CommentController@deleteUnVerifiedComments', 'as' => 'comment.delete-un-verified']);

/***
 * post
 */

Route::post('/post/{post}/restore', ['uses' => 'PostController@restore', 'as' => 'post.restore']);
Route::get('/post/{slug}/preview', ['uses' => 'PostController@preview', 'as' => 'post.preview']);
Route::post('/post/{post}/publish', ['uses' => 'PostController@publish', 'as' => 'post.publish']);
Route::get('/post/{post}/download', ['uses' => 'PostController@download', 'as' => 'post.download']);
Route::post('/post/{post}/config', ['uses' => 'PostController@updateConfig', 'as' => 'post.config']);
Route::get('/post/download-all', ['uses' => 'PostController@downloadAll', 'as' => 'post.download-all']);

/**
 * admin resource
 */
Route::resource('post', 'PostController', ['except' => ['show', 'index']]);
Route::resource('category', 'CategoryController', ['except' => ['index', 'show', 'create']]);
Route::resource('tag', 'TagController', ['except' => ['index', 'show', 'create']]);
Route::resource('page', 'PageController', ['except' => ['show', 'index']]);

/**
 * IPS
 */
Route::delete('/ip/{ip}/toggle', ['uses' => 'IpController@toggleBlock', 'as' => 'ip.block']);
Route::delete('/ip/{ip}', ['uses' => 'IpController@destroy', 'as' => 'ip.delete']);
Route::delete('/ip', ['uses' => 'IpController@deleteUnBlocked', 'as' => 'ip.delete-unblocked']);

/**
 * failed jobs
 */

Route::delete('/failed-jobs', ['uses' => 'AdminController@flushFailedJobs', 'as' => 'admin.failed-jobs.flush']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Site route
Route::get('/', ['uses' => 'HomeController@index', 'as' => 'index']);
Route::get('/projects', ['uses' => 'HomeController@projects', 'as' => 'projects']);
Route::get('/search', ['uses' => 'HomeController@search', 'as' => 'search']);
Route::get('/timeline', ['uses' => 'HomeController@achieve', 'as' => 'achieve']);

// User Auth
Auth::routes();
Route::get('/auth/github', ['uses' => 'Auth\AuthController@redirectToGithub', 'as' => 'github.login']);
Route::get('/auth/github/callback', ['uses' => 'Auth\AuthController@handleGithubCallback', 'as' => 'github.callback']);
Route::get('/github/register', ['uses' => 'Auth\AuthController@registerFromGithub', 'as' => 'github.register']);
Route::post('/github/store', ['uses' => 'Auth\AuthController@store', 'as' => 'github.store']);

// User
Route::get('/user/{name}', ['uses' => 'UserController@show', 'as' => 'user.show']);
Route::get('/user/me/settings', ['uses' => 'UserController@settings', 'as' => 'user.settings']);
Route::get('/user/me/pictures', ['uses' => 'UserController@pictures', 'as' => 'user.pictures']);
Route::get('/user/me/socials', ['uses' => 'UserController@socials', 'as' => 'user.socials']);
Route::get('/notifications', ['uses' => 'UserController@notifications', 'as' => 'user.notifications']);
Route::delete('/notifications', ['uses' => 'UserController@deleteReadNotifications', 'as' => 'user.delete_read_notifications']);
Route::get('/read_notification/{id}', ['uses' => 'UserController@readNotification', 'as' => 'user.read_notification']);
Route::get('/delete_notification/{id}', ['uses' => 'UserController@deleteNotification', 'as' => 'user.delete_notification']);
Route::patch('/user/update/avatar', ['uses' => 'UserController@updateAvatar', 'as' => 'user.update.avatar']);
Route::patch('/user/update/profile', ['uses' => 'UserController@updateProfile', 'as' => 'user.update.profile']);
Route::patch('/user/update/info', ['uses' => 'UserController@update', 'as' => 'user.update.info']);


// Post
Route::get('/vagas', ['uses' => 'PostController@index', 'as' => 'post.index']);
Route::get('/vagas/{slug}', ['uses' => 'PostController@show', 'as' => 'post.show']);

// Category
Route::get('/category/{name}', ['uses' => 'CategoryController@show', 'as' => 'category.show']);
Route::get('/category', ['uses' => 'CategoryController@index', 'as' => 'category.index']);

// Tag
Route::get('/tag/{name}', ['uses' => 'TagController@show', 'as' => 'tag.show']);
Route::get('/tag', ['uses' => 'TagController@index', 'as' => 'tag.index']);

// Comment
Route::get('/commentable/{commentable_id}/comments', ['uses' => 'CommentController@show', 'as' => 'comment.show']);
Route::get('comment/{comment}', ['uses' => 'CommentController@edit', 'as' => 'comment.edit']);

// SiteMap
Route::get('sitemap', 'GeneratedController@index');
Route::get('sitemap.xml', 'GeneratedController@index');

// Feed
Route::get('feed.xml', 'GeneratedController@feed')->name('feed');

// Comment
Route::resource('comment', 'CommentController', ['only' => ['store', 'destroy', 'edit', 'update']]);

/*
 * must last
 */
Route::get('/{name}', ['uses' => 'PageController@show', 'as' => 'page.show']);

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Repositories\PostRepository;
use App\Http\Repositories\UserRepository;
use App\Post;
use Illuminate\Http\Request;
use XblogConfig;

class HomeController extends Controller
{
    protected $postRepository;
    protected $userRepository;

    /**
     * Create a new controller instance.
     *
     * @param PostRepository $postRepository
     */
    public function __construct(PostRepository $postRepository, UserRepository $userRepository)
    {
        $this->postRepository = $postRepository;
        $this->userRepository = $userRepository;
    }

    public function index()
    {
        $totalUsers = $this->userRepository->count();
        $users = $this->userRepository->countUsers();
        $enterprises = $this->userRepository->countEditor();
        $jobs = $this->postRepository->postCount();
        return view('index', compact('totalUsers', 'users', 'enterprises', 'jobs'));
    }

    public function search(Request $request)
    {
        $key = trim($request->get('q'));
        if ($key == '')
            return back()->withErrors(__('web.PLEASE_KEY_IN_KEYWORD'));
        $page_size = XblogConfig::getValue('page_size', 7);
        $key = "%$key%";
        $posts = Post::where('title', 'like', $key)
            ->orWhere('description', 'like', $key)
            ->with(['tags', 'category'])
            ->withCount('comments')
            ->orderBy('view_count', 'desc')
            ->paginate($page_size);
        $posts->appends($request->except('page'));
        return view('search', compact('posts'));
    }

    public function projects()
    {
        return view('projects');
    }

    public function achieve()
    {
        $posts = $this->postRepository->achieve();
        $posts_count = $this->postRepository->postCount();
        return view('achieve', compact('posts', 'posts_count'));
    }

}

resources/views/admin/categories.blade.php
@extends('admin.layouts.app')
@section('title','Categories')
@section('content')
@section('action')
    <button class="btn btn-sm btn-outline-success" data-toggle="modal" data-target="#add-category-modal">New</button>
@endsection
<table class="table table-striped">
    <thead>
    <tr>
        <th>{{__('web.NAME')}}</th>
        <th>{{__('web.DESCRIPTION')}}</th>
        <th>{{__('web.ARTICLE')}}</th>
        <th>{{__('web.OPERATING')}}</th>
    </tr>
    </thead>
    <tbody>
    @foreach($categories as $category)
        <tr>
            <td>{{ $category->name }}</td>
            <td>{{ str_limit($category->description, 64) }}</td>
            <td>{{ $category->posts_count }}</td>
            <td>
                <div>
                    <a href="{{ route('category.edit',$category->id) }}" class="btn btn-info"
                       data-toggle="tooltip" data-placement="top" title="{{__('web.EDIT')}}">
                        <i class="fa fa-pencil fa-fw"></i>
                    </a>
                    <button class="btn btn-danger swal-dialog-target"
                            data-toggle="tooltip" data-placement="top" title="{{__('web.REMOVE')}}"
                            data-url="{{ route('category.destroy',$category->id) }}"
                            data-dialog-msg="{{__('web.REMOVE')}}{{ $category->name }}?">
                        <i class="fa fa-trash-o fa-fw"></i>
                    </button>
                </div>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
    @include('admin.modals.add-category-modal')
@endsection

resources/views/admin/comments.blade.php
@extends('admin.layouts.app')
@section('title','Comments')
@section('content')
@section('action')
    @if($unverified_count>0)
        <button class="btn btn-sm btn-outline-danger swal-dialog-target"
                data-dialog-msg="{{__('web.REMOVE')}} {{ $unverified_count }} {{__('web.UNVERIFIED_COMMENT')}}"
                data-url="{{ route('comment.delete-un-verified', ['ids'=>$unverified_ids]) }}"
                data-method="delete">{{__('web.DELETE_UNVERIFIED')}}
        </button>
    @endif
@endsection
@if($comments->isEmpty())
    <h3 class="center-block meta-item">No Comments</h3>
@else
    <table class="table table-striped" id="comments-table">
        <thead>
        <tr>
            {{--<th><input type="checkbox" name="select_all"></th>--}}
            <th>{{__('web.USER')}}</th>
            <th>{{__('web.E_MAIL')}}</th>
            <th>{{__('web.ADDRESS')}}</th>
            <th>{{__('web.STATUS')}}</th>
            <th>IP</th>
            <th>{{__('web.OPERATING')}}</th>
        </tr>
        </thead>
        <tbody>
        @foreach($comments as $comment)
            <?php $commentableData = $comment->getCommentableData();?>
            <tr id="{{ $comment->id }}">
                {{--<td><input type="checkbox"></td>--}}
                <td>
                    @if($comment->user_id)
                        <a href="{{ route('user.show',$comment->username) }}">{{ $comment->username }}</a>
                    @else
                        {{ $comment->username }}
                    @endif
                </td>
                <td><a href="mailto:{{ $comment->email }}">{{ $comment->email }}</a></td>
                <td>
                    @if($commentableData['deleted'])
                        <span data-html="true" data-toggle="tooltip" title="{{ $comment->html_content }}">{{ $commentableData['type'] }}
                            {{__('web.IS_REMOVE')}}</span>
                    @else
                        @if($comment->trashed())
                            <span data-html="true" data-toggle="tooltip"
                                  title="{{ $comment->html_content }}">{{ $commentableData['title'] }}</span>
                        @else
                            <a data-html="true" data-toggle="tooltip" title="{{ $comment->html_content }}"
                               target="_blank"
                               href="{{ $commentableData['url'] }}">{{$commentableData['title'] }}
                            </a>
                        @endif
                    @endif
                </td>
                <td>
                    <span class="p-2 p badge {{ $comment->trashed() ? 'badge-danger':($comment->isVerified() ? 'badge-success' : 'badge-secondary') }}">{{ $comment->trashed() ? __('web.IS_REMOVE'):($comment->isVerified() ? __('web.IS_VERIFIED') : __('web.NOT_VERIFIED')) }}</span>
                </td>
                <td>{{ $comment->ip_id?$comment->ip_id:'NONE' }}</td>
                <td>
                    @if($comment->trashed())
                        <button type="submit"
                                class="btn btn-danger swal-dialog-target"
                                data-dialog-msg="{{__('web.DELETE_THIS_COMMENT_FOREVER')}}？"
                                data-url="{{ route('comment.destroy',[$comment->id,'force'=>'true']) }}"
                                data-method="delete"
                                data-toggle="tooltip"
                                data-placement="top"
                                title="{{__('web.DELETE_FOREVER')}}">
                            <i class="fa fa-trash-o fa-fw"></i>
                        </button>
                        <form class="d-inline-block" method="post" action="{{ route('comment.restore',$comment->id) }}">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-primary" data-toggle="tooltip" data-placement="top"
                                    title="{{__('web.RECOVERY')}}">
                                <i class="fa fa-repeat fa-fw"></i>
                            </button>
                        </form>
                    @else
                        <button type="submit"
                                class="btn btn-danger swal-dialog-target"
                                data-dialog-msg="{{__('web.SURE_DELETE_THIS_COMMENT')}}？"
                                data-toggle="tooltip"
                                data-url="{{ route('comment.destroy',$comment->id) }}"
                                title="{{__('web.DELETE')}}">
                            <i class="fa fa-trash-o fa-fw"></i>
                        </button>
                        <a class="btn btn-info"
                           href="{{ route('comment.edit',[$comment->id,'redirect'=>request()->fullUrl()]) }}">
                            <i class="fa fa-pencil fa-fw"></i>
                        </a>
                    @endif
                    <form class="d-inline-block" method="post"
                          action="{{ route('comment.verify',$comment->id) }}">
                        {{ csrf_field() }}
                        <button type="submit" class="btn btn-info"
                                data-toggle="tooltip" data-placement="top"
                                title="{{ $comment->isVerified()?'Un Verify':'Verify' }}">
                            <i class="fa fa-{{ $comment->isVerified()?'hand-o-down':'hand-o-up' }} fa-fw"></i>
                        </button>
                    </form>
                    <?php $ip = $comment->ip ? $comment->ip : $comment->ip_id ?>
                    @if($ip == null)
                        <button disabled
                                class="btn btn-default"
                                data-toggle="tooltip"
                                title="NO IP">
                            <i class="fa fa-close fa-fw"></i>
                        </button>
                    @else
                        @include('admin.partials.ip_button',['ip'=>$ip])
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @if($comments->lastPage() > 1)
        {{ $comments->links() }}
    @endif
@endif
@endsection
{{--
@section('script')
    <script>
        let dataTable = document.getElementById('comments-table');
        let checkItAll = dataTable.querySelector('input[name="select_all"]');
        let inputs = dataTable.querySelectorAll('tbody>tr>td>input');
        let items = dataTable.querySelectorAll('tbody>tr');
        inputs.forEach(function (input) {
            input.addEventListener('change', function () {
                if (!this.checked) {
                    checkItAll.checked = false;
                } else if (!checkItAll.checked) {
                    let allChecked = true;
                    for (let i = 0; i < inputs.length; i++) {
                        if (!inputs[i].checked) {
                            allChecked = false;
                            break;
                        }
                    }

                    if (allChecked) {
                        checkItAll.checked = true;
                    }
                }
            });
        });

        checkItAll.addEventListener('change', function () {
            inputs.forEach(function (input) {
                input.checked = checkItAll.checked;
            });
        });

        function hh() {
            let ids = [];
            for (let i = 0; i < inputs.length; i++) {
                if (inputs[i].checked) {
                    ids.push(items[i].id)
                }
            }
            console.log(ids)
        }
    </script>
@endsection
--}}

resources/views/admin/ips.blade.php
@extends('admin.layouts.app')
@section('title','IPs')
@section('content')
    @if($ips->isEmpty())
        <div class="text-center"> -_- NO IP.</div>
    @else
@section('action')
    <div class="btn-group">
        <button class="btn btn-sm btn-outline-secondary" href="{{ route('admin.ips',['blocked'=>1]) }}">Blocked</button>
        <button class="swal-dialog-target btn btn-sm btn-outline-secondary"
           data-dialog-msg="Delete all unblocked IPs? "
           data-toggle="tooltip"
           title="Delete Unblocked IPs"
           data-url="{{ route('ip.delete-unblocked') }}"
           data-method="delete">DUI
        </button>
    </div>
@endsection
<table class="table table-striped">
    <thead>
    <tr>
        <th>IP</th>
        <th>Last User</th>
        <th>{{__('web.COMMENT_NUM')}}</th>
        <th>{{__('web.OPERATING')}}</th>
    </tr>
    </thead>
    <tbody>
    @foreach($ips as $ip)
        <tr>
            <td><a href="https://ip.sb/ip/{{ $ip->id }}" target="_blank">{{ $ip->id }}</a></td>
            @if($ip->user)
                <td>
                    <a href="{{ route('user.show',$ip->user->name) }}">{{ $ip->user->name }}</a>
                    @if(isAdminById($ip->user_id))
                        <span class="role-label">Admin</span>
                    @endif
                </td>
            @else
                <td>NONE</td>
            @endif
            <td>{{ $ip->comments_count }}</td>
            <td>
                @include('admin.partials.ip_button',['ip'=>$ip])
                <button class="btn btn-info swal-dialog-target"
                        data-toggle="tooltip"
                        title="{{__('web.REMOVE')}}"
                        data-url="{{ route('ip.delete',$ip->id) }}"
                        data-dialog-msg="{{__('web.CONFIRM_TO_REMOVE')}}IP{{ $ip->id }}?">
                    <i class="fa fa-trash-o fa-fw"></i>
                </button>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
@if($ips->lastPage() > 1)
    {{ $ips->links() }}
@endif
@endif
@endsection

resources/views/admin/pages.blade.php
@extends('admin.layouts.app')
@section('title','Pages')
@section('content')
@section('action')
    <a class="btn btn-sm btn-outline-success" href="{{ route('page.create') }}">New</a>
@endsection
@if($pages->isEmpty())
    <div class="center-block">No pages.</div>
@else
    <table class="table table-striped">
        <thead>
        <tr>
            <th>{{__('web.NAME')}}</th>
            <th>url</th>
            <th>{{__('web.OPERATING')}}</th>
        </tr>
        </thead>
        <tbody>
        @foreach($pages as $page)
            <tr>
                <td>{{ $page->display_name }}</td>
                <td>/{{ $page->name }}</td>
                <td>
                    <div>

                        <a href="{{ route('page.edit',$page->id) }}"
                           data-toggle="tooltip" data-placement="top" title="编辑"
                           class="btn btn-info">
                            <i class="fa fa-pencil fa-fw"></i>
                        </a>
                        <a href="/{{ $page->name }}"
                           data-toggle="tooltip" data-placement="top" title="查看"
                           class="btn btn-success">
                            <i class="fa fa-eye fa-fw"></i>
                        </a>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endif
@endsection

resources/views/admin/posts.blade.php
@extends('admin.layouts.app')
@section('title','Posts')
@section('content')
    @section('action')
        <a data-toggle="tooltip" data-placement="left" title="Download all posts as markdown file" class="btn btn-sm btn-outline-dark" href="{{ route('post.download-all') }}">Download</a>
    @endsection
    <table class="table table-striped">
        <thead>
        <tr>
            <th>{{__('web.TITLE')}}</th>
            <th>{{__('web.STATUS')}}</th>
            <th>{{__('web.OPERATING')}}</th>
        </tr>
        </thead>
        <tbody>
        @foreach($posts as $post)
            <?php
            $class = 'badge-secondary';
            $status = __('web.UNPUBLISHED');
            if ($post->trashed()) {
                $class = 'badge-danger';
                $status = __('web.IS_REMOVE');
            } else if ($post->isPublished()) {
                $class = 'badge-success';
                $status = __('web.PUBLISHED');
            }
            ?>
            <tr>
                <td title="{{ $post->title }}">{{ str_limit($post->title,64) }}</td>
                <td><span class="p-2 p badge {{ $class }}">{{ $status }}</span></td>
                <td>
                    <div>
                        <a {{ $post->trashed()?'disabled':'' }} href="{{ $post->trashed()?'javascript:void(0)':route('post.edit',$post->id) }}"
                           data-toggle="tooltip" data-placement="top" title="{{__('web.EDIT')}}"
                           class="btn btn-info">
                            <i class="fa fa-pencil fa-fw"></i>
                        </a>
                        @if($post->trashed())
                            <form style="display: inline" method="post" action="{{ route('post.restore',$post->id) }}">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-primary" data-toggle="tooltip"
                                        data-placement="top" title="{{__('web.RECOVERY')}}">
                                    <i class="fa fa-repeat fa-fw"></i>
                                </button>
                            </form>

                        @elseif($post->isPublished())
                            <a href="{{ route('post.show',$post->slug) }}"
                               data-toggle="tooltip" data-placement="top" title="{{__('web.CHECK')}}"
                               class="btn btn-success">
                                <i class="fa fa-eye fa-fw"></i>
                            </a>
                            <form style="display: inline" method="post"
                                  action="{{ route('post.publish',$post->id) }}">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-warning" data-toggle="tooltip"
                                        data-placement="top" title="{{__('web.REVOKE')}}{{__('web.PUBLISH')}}">
                                    <i class="fa fa-undo fa-fw"></i>
                                </button>
                            </form>
                        @else
                            <a href="{{ route('post.preview',$post->slug) }}" data-toggle="tooltip"
                               data-placement="top" title="{{__('web.REVIEW')}}"
                               class="btn btn-success">
                                <i class="fa fa-eye fa-fw"></i>
                            </a>
                            <form style="display: inline" method="post"
                                  action="{{ route('post.publish',$post->id) }}">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="{{__('web.PUBLISH')}}">
                                    <i class="fa fa-send-o fa-fw"></i>
                                </button>
                            </form>
                        @endif
                        <button class="btn btn-danger swal-dialog-target"
                                data-toggle="tooltip"
                                data-title="{{ $post->title }}"
                                data-dialog-msg="{{__('web.CONFIRM_TO_REMOVE')}}{{__('web.ARTICLE')}}<label>{{ $post->title }}</label>？"
                                title="{{__('web.REMOVE')}}"
                                data-dialog-enable-html="1"
                                data-url="{{ route('post.destroy',$post->id) }}"
                                data-dialog-confirm-text="{{ $post->trashed()?__('web.REMOVE_TIPS'):__('web.REMOVE') }}">
                            <i class="fa fa-trash-o  fa-fw"></i>
                        </button>
                        <a class="btn btn-dark"  data-toggle="tooltip" title="Download as markdown file" href="{{ route('post.download',$post->id) }}">
                            <i class="fa fa-cloud-download fa-fw"></i>
                        </a>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{__('web.COMMENTS')}}
                                <span class="caret"></span>
                            </button>
                            <?php $commentable = $post?>
                            <ul class="dropdown-menu">
                                @if($commentable->allowComment())
                                    <a href="#" data-url="{{ route('post.config',$post->id) }}?allow_resource_comment=false"
                                       data-method="post"
                                       data-dialog-title="{{__('web.DISALLOW_COMMENT')}}"
                                       class="dropdown-item swal-dialog-target">
                                        {{__('web.DISALLOW_COMMENT')}}
                                    </a>
                                @else
                                    <a href="#" data-url="{{ route('post.config',$post->id) }}?allow_resource_comment=true"
                                       data-method="post"
                                       data-dialog-title="{{__('web.ALLOW_COMMENT')}}"
                                       data-dialog-type="success"
                                       class="dropdown-item swal-dialog-target">
                                        {{__('web.ALLOW_COMMENT')}}
                                    </a>
                                @endif
                                @if($commentable->isShownComment())
                                    <a href="#" data-url="{{ route('post.config',$post->id) }}?comment_info=force_disable"
                                       data-method="post"
                                       data-dialog-title="{{__('web.HIDE_COMMENT')}}"
                                       class="dropdown-item swal-dialog-target">
                                        {{__('web.HIDE_COMMENT')}}
                                    </a>
                                @else
                                    <a href="#" data-url="{{ route('post.config',$post->id) }}?comment_info=force_enable"
                                       data-method="post"
                                       data-dialog-title="{{__('web.DISPLAT_COMMENT')}}"
                                       data-dialog-type="success"
                                       class="dropdown-item swal-dialog-target">
                                        {{__('web.DISPLAY_COMMENT')}}
                                    </a>
                                @endif
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $posts->links() }}
@endsection

resources/views/admin/tags.blade.php
@extends('admin.layouts.app')
@section('title','Tags')
@section('content')
@section('action')
    <button class="btn btn-sm btn-outline-success" data-toggle="modal" data-target="#add-tag-modal">New</button>
@endsection
    <table class="table table-striped">
        <thead>
        <tr>
            <th>{{__('web.NAME')}}</th>
            <th>{{__('web.ARTICLE')}}</th>
            <th>{{__('web.OPERATING')}}</th>
        </tr>
        </thead>
        <tbody>
        @foreach($tags as $tag)
            <tr>
                <td>{{ $tag->name }}</td>
                <td>{{ $tag->posts_count }}</td>
                <td>
                    <a href="{{ route('tag.edit',$tag->id) }}" class="btn btn-info"
                       data-toggle="tooltip" data-placement="top" title="{{__('web.EDIT2')}}">
                        <i class="fa fa-pencil fa-fw"></i>
                    </a>
                    <button type="submit"
                            data-toggle="tooltip"
                            class="btn btn-danger swal-dialog-target"
                            data-dialog-msg="{{ __('web.SURE_TO_DELETE').$tag->name }}？"
                            data-url="{{ route('tag.destroy',$tag->id) }}"
                            title="{{__('web.REMOVE')}}">
                        <i class="fa fa-trash-o fa-fw"></i>
                    </button>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @include('admin.modals.add-tag-modal')
@endsection