routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register Admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "web", "auth" and "admin" middleware groups. Enjoy building your Admin!
|
*/

/**
 * admin url
 */
Route::get('/', ['uses' => 'AdminController@index', 'as' => 'admin.index']);
Route::get('/settings', ['uses' => 'AdminController@settings', 'as' => 'admin.settings']);
Route::post('/settings', ['uses' => 'AdminController@saveSettings', 'as' => 'admin.save-settings']);
Route::post('/upload/image', ['uses' => 'ImageController@uploadImage', 'as' => 'upload.image']);
Route::delete('/delete/file', ['uses' => 'FileController@deleteFile', 'as' => 'delete.file']);
Route::post('/upload/file', ['uses' => 'FileController@uploadFile', 'as' => 'upload.file']);


/**
 * admin uri
 */
Route::get('/posts', ['uses' => 'AdminController@posts', 'as' => 'admin.posts']);
Route::get('/comments', ['uses' => 'AdminController@comments', 'as' => 'admin.comments']);
Route::get('/tags', ['uses' => 'AdminController@tags', 'as' => 'admin.tags']);
Route::get('/users', ['uses' => 'AdminController@users', 'as' => 'admin.users']);
Route::get('/pages', ['uses' => 'AdminController@pages', 'as' => 'admin.pages']);
Route::get('/categories', ['uses' => 'AdminController@categories', 'as' => 'admin.categories']);
Route::get('/images', ['uses' => 'ImageController@images', 'as' => 'admin.images']);
Route::get('/images-list', ['uses' => 'ImageController@images_list', 'as' => 'admin.images-list']);
Route::get('/files', ['uses' => 'FileController@files', 'as' => 'admin.files']);
Route::get('/ips', ['uses' => 'AdminController@ips', 'as' => 'admin.ips']);
Route::get('/app', ['uses' => 'AppController@index', 'as' => 'admin.app']);
Route::post('/app/email', ['uses' => 'AppController@sendMail', 'as' => 'admin.app.send-mail']);

/**
 * comment
 */
Route::post('/comment/{comment}/restore', ['uses' => 'CommentController@restore', 'as' => 'comment.restore']);
Route::match(['get', 'post'], '/comment/{comment}/verify', ['uses' => 'CommentController@verify', 'as' => 'comment.verify']);
Route::delete('comment/un-verified', ['uses' => 'CommentController@deleteUnVerifiedComments', 'as' => 'comment.delete-un-verified']);

/***
 * post
 */

Route::post('/post/{post}/restore', ['uses' => 'PostController@restore', 'as' => 'post.restore']);
Route::get('/post/{slug}/preview', ['uses' => 'PostController@preview', 'as' => 'post.preview']);
Route::post('/post/{post}/publish', ['uses' => 'PostController@publish', 'as' => 'post.publish']);
Route::get('/post/{post}/download', ['uses' => 'PostController@download', 'as' => 'post.download']);
Route::post('/post/{post}/config', ['uses' => 'PostController@updateConfig', 'as' => 'post.config']);
Route::get('/post/download-all', ['uses' => 'PostController@downloadAll', 'as' => 'post.download-all']);

/**
 * admin resource
 */
Route::resource('post', 'PostController', ['except' => ['show', 'index']]);
Route::resource('category', 'CategoryController', ['except' => ['index', 'show', 'create']]);
Route::resource('tag', 'TagController', ['except' => ['index', 'show', 'create']]);
Route::resource('page', 'PageController', ['except' => ['show', 'index']]);

/**
 * IPS
 */
Route::delete('/ip/{ip}/toggle', ['uses' => 'IpController@toggleBlock', 'as' => 'ip.block']);
Route::delete('/ip/{ip}', ['uses' => 'IpController@destroy', 'as' => 'ip.delete']);
Route::delete('/ip', ['uses' => 'IpController@deleteUnBlocked', 'as' => 'ip.delete-unblocked']);

/**
 * failed jobs
 */

Route::delete('/failed-jobs', ['uses' => 'AdminController@flushFailedJobs', 'as' => 'admin.failed-jobs.flush']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Site route
Route::get('/', ['uses' => 'HomeController@index', 'as' => 'index']);
Route::get('/projects', ['uses' => 'HomeController@projects', 'as' => 'projects']);
Route::get('/search', ['uses' => 'HomeController@search', 'as' => 'search']);
Route::get('/timeline', ['uses' => 'HomeController@achieve', 'as' => 'achieve']);

// User Auth
Auth::routes();
Route::get('/auth/github', ['uses' => 'Auth\AuthController@redirectToGithub', 'as' => 'github.login']);
Route::get('/auth/github/callback', ['uses' => 'Auth\AuthController@handleGithubCallback', 'as' => 'github.callback']);
Route::get('/github/register', ['uses' => 'Auth\AuthController@registerFromGithub', 'as' => 'github.register']);
Route::post('/github/store', ['uses' => 'Auth\AuthController@store', 'as' => 'github.store']);

// User
Route::get('/user/{name}', ['uses' => 'UserController@show', 'as' => 'user.show']);
Route::get('/user/me/settings', ['uses' => 'UserController@settings', 'as' => 'user.settings']);
Route::get('/user/me/pictures', ['uses' => 'UserController@pictures', 'as' => 'user.pictures']);
Route::get('/user/me/socials', ['uses' => 'UserController@socials', 'as' => 'user.socials']);
Route::get('/notifications', ['uses' => 'UserController@notifications', 'as' => 'user.notifications']);
Route::delete('/notifications', ['uses' => 'UserController@deleteReadNotifications', 'as' => 'user.delete_read_notifications']);
Route::get('/read_notification/{id}', ['uses' => 'UserController@readNotification', 'as' => 'user.read_notification']);
Route::get('/delete_notification/{id}', ['uses' => 'UserController@deleteNotification', 'as' => 'user.delete_notification']);
Route::patch('/user/update/avatar', ['uses' => 'UserController@updateAvatar', 'as' => 'user.update.avatar']);
Route::patch('/user/update/profile', ['uses' => 'UserController@updateProfile', 'as' => 'user.update.profile']);
Route::patch('/user/update/info', ['uses' => 'UserController@update', 'as' => 'user.update.info']);


// Post
Route::get('/vagas', ['uses' => 'PostController@index', 'as' => 'post.index']);
Route::get('/vagas/{slug}', ['uses' => 'PostController@show', 'as' => 'post.show']);

// Category
Route::get('/category/{name}', ['uses' => 'CategoryController@show', 'as' => 'category.show']);
Route::get('/category', ['uses' => 'CategoryController@index', 'as' => 'category.index']);

// Tag
Route::get('/tag/{name}', ['uses' => 'TagController@show', 'as' => 'tag.show']);
Route::get('/tag', ['uses' => 'TagController@index', 'as' => 'tag.index']);

// Comment
Route::get('/commentable/{commentable_id}/comments', ['uses' => 'CommentController@show', 'as' => 'comment.show']);
Route::get('comment/{comment}', ['uses' => 'CommentController@edit', 'as' => 'comment.edit']);

// SiteMap
Route::get('sitemap', 'GeneratedController@index');
Route::get('sitemap.xml', 'GeneratedController@index');

// Feed
Route::get('feed.xml', 'GeneratedController@feed')->name('feed');

// Comment
Route::resource('comment', 'CommentController', ['only' => ['store', 'destroy', 'edit', 'update']]);

/*
 * must last
 */
Route::get('/{name}', ['uses' => 'PageController@show', 'as' => 'page.show']);

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Repositories\PostRepository;
use App\Http\Repositories\UserRepository;
use App\Post;
use Illuminate\Http\Request;
use XblogConfig;

class HomeController extends Controller
{
    protected $postRepository;
    protected $userRepository;

    /**
     * Create a new controller instance.
     *
     * @param PostRepository $postRepository
     */
    public function __construct(PostRepository $postRepository, UserRepository $userRepository)
    {
        $this->postRepository = $postRepository;
        $this->userRepository = $userRepository;
    }

    public function index()
    {
        $totalUsers = $this->userRepository->count();
        $users = $this->userRepository->countUsers();
        $enterprises = $this->userRepository->countEditor();
        $jobs = $this->postRepository->postCount();
        return view('index', compact('totalUsers', 'users', 'enterprises', 'jobs'));
    }

    public function search(Request $request)
    {
        $key = trim($request->get('q'));
        if ($key == '')
            return back()->withErrors(__('web.PLEASE_KEY_IN_KEYWORD'));
        $page_size = XblogConfig::getValue('page_size', 7);
        $key = "%$key%";
        $posts = Post::where('title', 'like', $key)
            ->orWhere('description', 'like', $key)
            ->with(['tags', 'category'])
            ->withCount('comments')
            ->orderBy('view_count', 'desc')
            ->paginate($page_size);
        $posts->appends($request->except('page'));
        return view('search', compact('posts'));
    }

    public function projects()
    {
        return view('projects');
    }

    public function achieve()
    {
        $posts = $this->postRepository->achieve();
        $posts_count = $this->postRepository->postCount();
        return view('achieve', compact('posts', 'posts_count'));
    }

}

resources/views/widget/categories.blade.php
@if(!$categories->isEmpty())
    <div class="order-md-2 mb-4">
        <h5 class="d-flex justify-content-between align-items-center mb-2">
            <a class="text-muted" href="{{ route('category.index') }}">{{__('web.CLASSIFICATION')}}</a>
            <span class="badge badge-secondary badge-pill">{{ count($categories) }}</span>
        </h5>
        <div class="hot-posts">
            <ul class="list-group shadow">
                @foreach($categories as $category)
                    @php
                        $is_current = request()->is('category/'.$category->name);
                    @endphp
                    <a class="{{ $is_current?'bg-light text-success ':'' }}border-0 list-group-item d-flex justify-content-between list-group-item-action"
                       href="{{ route('category.show',$category->name) }}" title="{{ $category->name }}">
                        <h6 class="my-0">{{ $category->name }}</h6>
                        <span class="text-{{ $is_current?'success':'muted' }}">{{ $category->posts_count }}</span>
                    </a>
                @endforeach
            </ul>
        </div>
    </div>
@endif

resources/views/widget/comment.blade.php
<?php
$final_comment_type = $commentable->getCommentType();
?>
@if($final_comment_type == 'raw')
    @include('widget.raw_comment')
@elseif($final_comment_type == 'disqus')
    @include('widget.disqus_comment')
@endif

resources/views/widget/disqus_comment.blade.php
<div class="comments shadow" id="comments">
    <div class="comments-body">
        <section id="comments">
            <div id="disqus_thread"></div>
        </section>
        <script type="text/javascript">
            var disqus_shortname = '{{ $disqus_shortname }}';
            var disqus_url = '{{ $comment_url }}';
            var disqus_title = '{{ $comment_title }}';
            (function(){
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = 'https://go.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
    </div>
</div>

resources/views/widget/google_analytics.blade.php
@if(isset($google_analytics) && $google_analytics == 'true')
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ $google_trace_id or '' }}"></script>
    <script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', "{{ $google_trace_id or '' }}");</script>
@endif

resources/views/widget/hot_posts.blade.php
<div class="order-md-2 mb-4">
    <h5 class="d-flex justify-content-between align-items-center mb-2">
        <span class="text-muted">{{__('web.POP_ARTICLES')}}</span>
        <span class="badge badge-secondary badge-pill">{{ count($hotPosts) }}</span>
    </h5>
    <div class="hot-posts">
        <ul class="list-group shadow">
            @foreach($hotPosts as $post)
                <a class=" border-0 list-group-item list-group-item-action" title="{{ $post->title }}" href="{{ route('post.show',$post->slug) }}">
                    <h6 class="my-0">{{ $post->title }}</h6>
                    <small class="text-muted">{{__('web.VIEWS')}}: {{ $post->view_count }}, {{__('web.COMMENTS')}}: {{ $post->comments_count }}</small>
                </a>
            @endforeach
        </ul>
    </div>
</div>

resources/views/widget/mathjax.blade.php
<script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        tex2jax: {
          inlineMath: [ ['$','$'], ["\\(","\\)"]  ],
          processEscapes: true,
          skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
        }
      });
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

resources/views/widget/pay.blade.php
@if(isset($open_pay) && $open_pay == 'true')
    <div class="pay mb-3">
        <div class="center">
            <p class="center-block">{{ $pay_description or __('web.WRITE_WELL_DONATE') }}</p>
            <button class="btn btn-success center" type="button"
                    data-toggle="collapse" data-target="#pay-content">
                {{__('web.DONATE')}}
            </button>
        </div>
        <div id="pay-content" class="collapse pay-content text-center">
            @if(isset($zhifubao_pay_image_url) && !empty($zhifubao_pay_image_url) && isset($wechat_pay_image_url) && !empty($wechat_pay_image_url))
                <div class="btn-group nav pay-buttons justify-content-center mt-3" role="group">
                    <a class="btn btn-light active" href="#zhifubao" role="tab" data-toggle="tab"
                       aria-controls="zhifubao">
                        {{__('web.ZHIFUBAO')}}
                    </a>
                    <a class="btn btn-light" href="#wechat" role="tab" data-toggle="tab"
                       aria-controls="wechat">
                        {{__('web.WECHAT')}}
                    </a>
                </div>
                <div class="tab-content pay-images">
                    <div id="zhifubao" role="tabpanel" class="tab-pane fade show active">
                        <span class="center-block">{{__('web.ZHIFUBAO_TABPANEL')}}</span>
                        <img src="{{ $zhifubao_pay_image_url }}">
                    </div>
                    <div id="wechat" role="tabpanel" class="tab-pane fade">
                        <span class="center-block">{{__('web.WECHAT_TABPANEL')}}</span>
                        <img src="{{ $wechat_pay_image_url }}">
                    </div>
                </div>
            @elseif(isset($zhifubao_pay_image_url) && !empty($zhifubao_pay_image_url))
                <div class="tab-content pay-images">
                    <div role="tabpanel" class="tab-pane fade show active">
                        <span class="center-block">{{__('web.ZHIFUBAO_TABPANEL')}}</span>
                        <img src="{{ $zhifubao_pay_image_url }}">
                    </div>
                </div>
            @elseif(isset($wechat_pay_image_url) && !empty($wechat_pay_image_url))
                <div class="tab-content pay-images">
                    <div role="tabpanel" class="tab-pane fade show active">
                        <span class="center-block">{{__('web.WECHAT_TABPANEL')}}</span>
                        <img src="{{ $wechat_pay_image_url }}">
                    </div>
                </div>
            @endif
        </div>
    </div>
@endif

resources/views/widget/raw_comment.blade.php
<div class="comments shadow" id="comments">
    <div class="comments-body">
        <div id="comments-container"
             data-api-url="{{ route('comment.show',[$commentable->id,
             'commentable_type'=>$commentable_type,
             'redirect'=>(isset($redirect) && $redirect ? $redirect:'')]) }}">
            @if(isset($comments) && !empty($comments))
                @include('comment.show',$comments)
            @endif
        </div>
        <div id="comment-form-wrapper">
            <form id="comment-form" method="post" action="{{ route('comment.store') }}" class="comment-form">
                {{ csrf_field() }}
                <input type="hidden" name="commentable_id" value="{{ $commentable->id }}">
                <input type="hidden" name="commentable_type" value="{{ $commentable_type }}">
                <?php $final_allow_comment = $commentable->allowComment()?>
                @if(!auth()->check())
                    <div class="form-group">
                        <label class="form-control-label" for="username">{{__('web.USERNAME')}}<span class="text-danger">*</span></label>
                        <input {{ $final_allow_comment?' ':' disabled ' }} class="form-control" id="username" type="text" name="username" placeholder="{{__('web.YOUR_NAME')}}">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="email">{{__('web.EMAIL')}}<span class="text-danger">*</span></label>
                        <input {{ $final_allow_comment?' ':' disabled ' }} class="form-control" id="email" type="email" name="email" placeholder="{{__('web.YOUR_EMAIL')}}">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="site">{{__('web.WEBSITE')}}</label>
                        <input {{ $final_allow_comment?' ':' disabled ' }} class="form-control" id="site" type="text" name="site" placeholder="{{__('web.YOUR_WEBSITE')}}">
                    </div>
                @endif
                <div class="form-group">
                    <label for="comment-content">{{__('web.COMMENT_ARTICLE')}},{{__('web.SUPPORT')}} <a href="https://daringfireball.net/projects/markdown/syntax">Markdown</a><span class="text-danger">*</span></label>
                    <textarea {{ $final_allow_comment?' ':' disabled ' }} placeholder="{{__('web.REVIEW_N_SHOW')}}"
                              id="comment-content" name="content"
                              rows="5" spellcheck="false"
                              class="form-control markdown-content autosize-target"></textarea>
                </div>
                @if($final_allow_comment)
                    <div class="g-recaptcha" data-sitekey="{{ config('recaptcha.api_site_key') }}" widget-id="0"></div>
                @endif
                <div class="form-group">
                    <span class="help-block required"><strong id="comment_submit_msg"></strong></span>
                </div>
                <div class="form-group">
                    <input {{ $final_allow_comment?' ':' disabled ' }} type="submit" id="comment-submit" class="btn btn-primary"
                           value="{{__('web.COMMENT_SUBMIT')}}"/>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/widget/recommended_posts.blade.php
@if(!$recommendedPosts->isEmpty())
    <div class="alert alert-dismissible fade show border-0 shadow" style="background-color: #fff;color:inherit;padding:15px 20px 10px;border-color:#ededed;border-radius: 0">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <label>{{__('web.RECOMMENDED_POSTS')}} :</label>
        @foreach($recommendedPosts as $post)
            <div style="padding-top: 5px;padding-bottom: 5px;">
                <a style="font-size: 1.15em" href="{{ route("post.show",$post->slug) }}">{{ str_limit($post->title,36) }}</a>
                <span style="color: #ccc;margin-left: 15px;">{{ $post->created_at->format('Y-m-d') }}</span>
            </div>
        @endforeach
    </div>
@endif

resources/views/widget/tags.blade.php
<div class="order-md-2 mb-4">
    <h5 class="d-flex justify-content-between align-items-center mb-2">
        <a class="text-muted" href="{{ route('tag.index') }}">{{__('web.TAG')}}</a>
        <span class="badge badge-secondary badge-pill">{{ count($tags) }}</span>
    </h5>
    <ul class="tags bg-white p-3 shadow rounded">
        @forelse($tags as $tag)
            @if(request()->is('tag/'.$tag->name))
                <li>
                    <span class="tag active" title="{{ $tag->name }}">
                        {{ $tag->name }}
                            <span class="font-weight-bold">{{ $tag->posts_count }}</span>
                    </span>
                </li>
            @else
                <li>
                    <a title="{{ $tag->name }}" href="{{ route('tag.show',$tag->name) }}" class="tag">
                        {{ $tag->name }}
                        <span class="font-weight-bold">{{ $tag->posts_count }}</span>
                    </a>
                </li>
            @endif
        @empty <p class="meta-item center-block">{{__('web.NO_TAGS')}}</p>
        @endforelse
    </ul>
</div>

resources/views/widget/user.blade.php
<div class="card card-user mb-4" style="overflow: hidden">
    <?php
    if (isset($profile_image) && $profile_image)
        $style = "background: url($profile_image) no-repeat center center;background-size: cover";
    else
        $style = '';
    ?>
    <div class="card-user-header bg-placeholder" style="{{ $style }}">
        <h3 class="card-user-username">{{ $author or '' }}</h3>
        <h5 class="card-user-desc">{{ $description or '' }}</h5>
    </div>
    <div class="card-user-image">
        <img class="rounded-circle"
             src="{{ $avatar or '/img/apoio-portador.png' }}"
             alt="User Avatar">
    </div>
    <div class="card-user-footer">
        <div class="row">
            @foreach(['facebook','twitter','instagram','linkedin'] as $social)
                <?php $social_link = "social_" . $social ?>
                @if(isset($$social_link) && $$social_link)
                    <div class="col">
                        <div class="description-block">
                            @include('partials.social_icon', ['name' => $social])
                        </div>
                    </div>
                @endif
            @endforeach
        </div>
    </div>

    @if(isset($other_information) && $other_information)
        {!! $other_information !!}
    @endif
</div>