routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register Admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "web", "auth" and "admin" middleware groups. Enjoy building your Admin!
|
*/

/**
 * admin url
 */
Route::get('/', ['uses' => 'AdminController@index', 'as' => 'admin.index']);
Route::get('/settings', ['uses' => 'AdminController@settings', 'as' => 'admin.settings']);
Route::post('/settings', ['uses' => 'AdminController@saveSettings', 'as' => 'admin.save-settings']);
Route::post('/upload/image', ['uses' => 'ImageController@uploadImage', 'as' => 'upload.image']);
Route::delete('/delete/file', ['uses' => 'FileController@deleteFile', 'as' => 'delete.file']);
Route::post('/upload/file', ['uses' => 'FileController@uploadFile', 'as' => 'upload.file']);


/**
 * admin uri
 */
Route::get('/posts', ['uses' => 'AdminController@posts', 'as' => 'admin.posts']);
Route::get('/comments', ['uses' => 'AdminController@comments', 'as' => 'admin.comments']);
Route::get('/tags', ['uses' => 'AdminController@tags', 'as' => 'admin.tags']);
Route::get('/users', ['uses' => 'AdminController@users', 'as' => 'admin.users']);
Route::get('/pages', ['uses' => 'AdminController@pages', 'as' => 'admin.pages']);
Route::get('/categories', ['uses' => 'AdminController@categories', 'as' => 'admin.categories']);
Route::get('/images', ['uses' => 'ImageController@images', 'as' => 'admin.images']);
Route::get('/images-list', ['uses' => 'ImageController@images_list', 'as' => 'admin.images-list']);
Route::get('/files', ['uses' => 'FileController@files', 'as' => 'admin.files']);
Route::get('/ips', ['uses' => 'AdminController@ips', 'as' => 'admin.ips']);
Route::get('/app', ['uses' => 'AppController@index', 'as' => 'admin.app']);
Route::post('/app/email', ['uses' => 'AppController@sendMail', 'as' => 'admin.app.send-mail']);

/**
 * comment
 */
Route::post('/comment/{comment}/restore', ['uses' => 'CommentController@restore', 'as' => 'comment.restore']);
Route::match(['get', 'post'], '/comment/{comment}/verify', ['uses' => 'CommentController@verify', 'as' => 'comment.verify']);
Route::delete('comment/un-verified', ['uses' => 'CommentController@deleteUnVerifiedComments', 'as' => 'comment.delete-un-verified']);

/***
 * post
 */

Route::post('/post/{post}/restore', ['uses' => 'PostController@restore', 'as' => 'post.restore']);
Route::get('/post/{slug}/preview', ['uses' => 'PostController@preview', 'as' => 'post.preview']);
Route::post('/post/{post}/publish', ['uses' => 'PostController@publish', 'as' => 'post.publish']);
Route::get('/post/{post}/download', ['uses' => 'PostController@download', 'as' => 'post.download']);
Route::post('/post/{post}/config', ['uses' => 'PostController@updateConfig', 'as' => 'post.config']);
Route::get('/post/download-all', ['uses' => 'PostController@downloadAll', 'as' => 'post.download-all']);

/**
 * admin resource
 */
Route::resource('post', 'PostController', ['except' => ['show', 'index']]);
Route::resource('category', 'CategoryController', ['except' => ['index', 'show', 'create']]);
Route::resource('tag', 'TagController', ['except' => ['index', 'show', 'create']]);
Route::resource('page', 'PageController', ['except' => ['show', 'index']]);

/**
 * IPS
 */
Route::delete('/ip/{ip}/toggle', ['uses' => 'IpController@toggleBlock', 'as' => 'ip.block']);
Route::delete('/ip/{ip}', ['uses' => 'IpController@destroy', 'as' => 'ip.delete']);
Route::delete('/ip', ['uses' => 'IpController@deleteUnBlocked', 'as' => 'ip.delete-unblocked']);

/**
 * failed jobs
 */

Route::delete('/failed-jobs', ['uses' => 'AdminController@flushFailedJobs', 'as' => 'admin.failed-jobs.flush']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Site route
Route::get('/', ['uses' => 'HomeController@index', 'as' => 'index']);
Route::get('/projects', ['uses' => 'HomeController@projects', 'as' => 'projects']);
Route::get('/search', ['uses' => 'HomeController@search', 'as' => 'search']);
Route::get('/timeline', ['uses' => 'HomeController@achieve', 'as' => 'achieve']);

// User Auth
Auth::routes();
Route::get('/auth/github', ['uses' => 'Auth\AuthController@redirectToGithub', 'as' => 'github.login']);
Route::get('/auth/github/callback', ['uses' => 'Auth\AuthController@handleGithubCallback', 'as' => 'github.callback']);
Route::get('/github/register', ['uses' => 'Auth\AuthController@registerFromGithub', 'as' => 'github.register']);
Route::post('/github/store', ['uses' => 'Auth\AuthController@store', 'as' => 'github.store']);

// User
Route::get('/user/{name}', ['uses' => 'UserController@show', 'as' => 'user.show']);
Route::get('/user/me/settings', ['uses' => 'UserController@settings', 'as' => 'user.settings']);
Route::get('/user/me/pictures', ['uses' => 'UserController@pictures', 'as' => 'user.pictures']);
Route::get('/user/me/socials', ['uses' => 'UserController@socials', 'as' => 'user.socials']);
Route::get('/notifications', ['uses' => 'UserController@notifications', 'as' => 'user.notifications']);
Route::delete('/notifications', ['uses' => 'UserController@deleteReadNotifications', 'as' => 'user.delete_read_notifications']);
Route::get('/read_notification/{id}', ['uses' => 'UserController@readNotification', 'as' => 'user.read_notification']);
Route::get('/delete_notification/{id}', ['uses' => 'UserController@deleteNotification', 'as' => 'user.delete_notification']);
Route::patch('/user/update/avatar', ['uses' => 'UserController@updateAvatar', 'as' => 'user.update.avatar']);
Route::patch('/user/update/profile', ['uses' => 'UserController@updateProfile', 'as' => 'user.update.profile']);
Route::patch('/user/update/info', ['uses' => 'UserController@update', 'as' => 'user.update.info']);


// Post
Route::get('/vagas', ['uses' => 'PostController@index', 'as' => 'post.index']);
Route::get('/vagas/{slug}', ['uses' => 'PostController@show', 'as' => 'post.show']);

// Category
Route::get('/category/{name}', ['uses' => 'CategoryController@show', 'as' => 'category.show']);
Route::get('/category', ['uses' => 'CategoryController@index', 'as' => 'category.index']);

// Tag
Route::get('/tag/{name}', ['uses' => 'TagController@show', 'as' => 'tag.show']);
Route::get('/tag', ['uses' => 'TagController@index', 'as' => 'tag.index']);

// Comment
Route::get('/commentable/{commentable_id}/comments', ['uses' => 'CommentController@show', 'as' => 'comment.show']);
Route::get('comment/{comment}', ['uses' => 'CommentController@edit', 'as' => 'comment.edit']);

// SiteMap
Route::get('sitemap', 'GeneratedController@index');
Route::get('sitemap.xml', 'GeneratedController@index');

// Feed
Route::get('feed.xml', 'GeneratedController@feed')->name('feed');

// Comment
Route::resource('comment', 'CommentController', ['only' => ['store', 'destroy', 'edit', 'update']]);

/*
 * must last
 */
Route::get('/{name}', ['uses' => 'PageController@show', 'as' => 'page.show']);

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use App\Http\Repositories\CategoryRepository;
use App\Http\Repositories\CommentRepository;
use App\Http\Repositories\PostRepository;
use App\Http\Repositories\TagRepository;
use App\Http\Requests;
use App\Notifications\UserRegistered;
use App\Post;
use Carbon\Carbon;
use Chumper\Zipper\Facades\Zipper;
use File;
use Gate;
use Illuminate\Http\Request;
use League\HTMLToMarkdown\HtmlConverter;
use XblogConfig;

class PostController extends Controller
{
    protected $postRepository;
    protected $tagRepository;
    protected $categoryRepository;
    protected $commentRepository;

    /**
     * PostController constructor.
     * @param PostRepository $postRepository
     * @param CategoryRepository $categoryRepository
     * @param TagRepository $tagRepository
     * @param CommentRepository $commentRepository
     */
    public function __construct(PostRepository $postRepository,
                                CategoryRepository $categoryRepository,
                                TagRepository $tagRepository,
                                CommentRepository $commentRepository)
    {
        $this->postRepository = $postRepository;
        $this->categoryRepository = $categoryRepository;
        $this->tagRepository = $tagRepository;
        $this->commentRepository = $commentRepository;
    }


    public function create()
    {
        if ($this->categoryRepository->count() <= 0) {
            return redirect()->route('admin.categories')->withErrors(__('web.PLEASE_CREATE_CATEGORY'));
        }
        return view('admin.post.create',
            [
                'categories' => $this->categoryRepository->getAll(),
                'tags' => $this->tagRepository->getAll(),
            ]
        );
    }

    public function store(Request $request)
    {
        $this->validatePostForm($request);
        $post = $this->postRepository->create($request);

        if ($post) {
            if ($post->isPublished()) {
                $link = route('post.show', $post->slug);
            } else {
                $link = route('post.preview', $post->slug);
            }
            return redirect('admin/posts')->with('success', __('web.ARTICLE') . "<a href='$link'>$post->title</a>" . __('web.CREATE_SUCCESS'));
        } else {
            return redirect('admin/posts')->withErrors(__('web.ARTICLE') . $request['name'] . __('web.CREATE_FAIL'));
        }
    }

    public function preview($slug)
    {
        $post = Post::withoutGlobalScopes()->where('slug', $slug)->with('tags')->first();
        if (!$post)
            abort(404);
        $preview = true;
        return view('post.show', compact('post', 'preview'));
    }

    public function publish($id)
    {
        $post = Post::withoutGlobalScopes()->find($id);
        if ($post->trashed()) {
            return back()->withErrors($post->title . __('web.PUBLISH_FAIL_REMOVE'));
        }
        $this->clearAllCache();
        if ($post->status == 0) {
            $post->status = 1;
            $post->published_at = Carbon::now();
            if ($post->save()) {
                $link = $this->getPostLink($post);
                return back()->with('success', "<a href='$link'>$post->title</a> " . __('web.PUBLISH_SUCCESS'));
            }
        } else if ($post->status == 1) {
            $post->status = 0;
            if ($post->save()) {
                $link = $this->getPostLink($post);
                return back()->with('success', "<a href='$link'>$post->title</a> " . __('web.REVOKE_PUBLISH_SUCCESS'));
            }
        }
        return back()->withErrors($post->title . __('web.OPERATING_FAIL'));
    }


    public function edit($id)
    {
        $post = Post::withoutGlobalScopes()->find($id);

        $this->checkPolicy('update', $post);

        $post->description = (new HtmlConverter(['header_style' => 'atx']))->convert($post->description);

        return view('admin.post.edit', [
            'post' => $post,
            'categories' => $this->categoryRepository->getAll(),
            'tags' => $this->tagRepository->getAll(),
        ]);
    }


    public function update(Request $request, $id)
    {
        $post = Post::withoutGlobalScopes()->find($id);
        $this->checkPolicy('update', $post);
        $this->validatePostForm($request, true);

        if ($this->postRepository->update($request, $post)) {
            $link = $this->getPostLink($post);
            return redirect('admin/posts')->with('success', "<a href='$link'>$post->title</a> " . __('web.EDIT_SUCCESS'));
        } else
            return redirect('admin/posts')->withErrors(__('web.ARTICLE') . $request['name'] . __('web.EDIT_FAIL'));
    }

    public function download($id)
    {
        $post = Post::withoutGlobalScopes()->where('id', $id)->with(['tags', 'category'])->first();
        $info = $this->getPostContent($post);
        return response($info, 200,
            [
                "Content-Type" => 'application/force-download',
                'Content-Disposition' => "attachment; filename=\"" . $post->title . ".md\""
            ]
        );
    }

    public function downloadAll()
    {
        $path = storage_path('post' . DIRECTORY_SEPARATOR . 'posts.zip');
        if (File::exists($path)) {
            File::delete($path);
        }
        $zipper = Zipper::make($path);
        foreach (Post::withoutGlobalScopes()->get() as $post) {
            $zipper->folder('posts')->addString($post->title . '.md', $this->getPostContent($post));
        }
        $zipper->close();
        return response()->download($path);
    }

    private function getPostContent(Post $post)
    {
        $info = "---\ntitle: " . $post->title;
        $info = $info . "\ncreated_at: " . $post->created_at;
        $info = $info . "\nslug: " . $post->slug;
        $info = $info . "\ncategory: " . $post->category->name;
        if ($post->tags) {
            $info = $info . "\ntags:\n";
            foreach ($post->tags as $tag) {
                $info = $info . "  - $tag->name\n";
            }
        }
        $info = $info . "\n---\n\n" . $post->content;
        return $info;
    }

    public function restore($id)
    {
        $post = Post::withoutGlobalScopes()->findOrFail($id);
        if ($post->trashed()) {
            $post->restore();
            $this->clearAllCache();
            $link = $this->getPostLink($post);
            return redirect()->route('admin.posts')->with('success', "<a href='$link'>$post->title</a>" . __('web.RECOVERY_SUCCESS'));
        }
        return redirect()->route('admin.posts')->withErrors(__('web.RECOVERY_FAIL'));
    }


    public function destroy($id)
    {
        $post = Post::withoutGlobalScopes()->findOrFail($id);
        $redirect = route('admin.posts');
        if (request()->has('redirect'))
            $redirect = request()->input('redirect');

        if ($post->trashed()) {
            $result = $post->forceDelete();
        } else {
            $result = $post->delete();
        }
        if ($result) {
            $this->clearAllCache();
            return redirect($redirect)->with('success', __('web.REMOVE'). $post->title.__('web.SUCCESS'));
        } else
            return redirect($redirect)->withErrors(__('web.REMOVE_FAIL'));
    }

    private function validatePostForm(Request $request, $update = false)
    {
        $v = [
            'cover_img' => 'nullable|url',
            'title' => 'required',
            'category_id' => 'required',
            'content' => 'required',
        ];
        if (!$update)
            $v = array_merge($v, ['slug' => 'required|unique:posts']);
        $this->validate($request, $v);
    }

    public function clearAllCache()
    {
        $this->postRepository->clearAllCache();
    }

    public function updateConfig(Request $request, $id)
    {
        $post = Post::withoutGlobalScopes()->findOrFail($id);
        if ($post->saveConfig($request->all()))
            return back()->withSuccess('Update configure successfully');
        return back()->withErrors('Update Configure failed');
    }

    private function getPostLink(Post $post)
    {
        if ($post->isPublished()) {
            $link = route('post.show', $post->slug);
        } else {
            $link = route('post.preview', $post->slug);
        }
        return $link;
    }
}

app/Http/Controllers/Editor/AppController.php
<?php

namespace App\Http\Controllers\Editor;

use App\Http\Controllers\Controller;
use App\Http\Repositories\IpRepository;
use Mail;
use Gate;
use DB;
use Illuminate\Http\Request;

class AppController extends Controller
{
    protected $ipRepository;

    public function __construct(IpRepository $ipRepository)
    {
        $this->ipRepository = $ipRepository;
    }

    public function index()
    {
        $failed_jobs = DB::table('failed_jobs')->get();
        return view('editor.app', compact('failed_jobs'));
    }

    public function sendMail(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email',
            'content' => 'required',
        ]);
        try {
            $result = Mail::raw($request['content'], function ($message) use ($request) {
                $message->subject('Test email from ' . config('app.name'));
                $message->to($request['email']);
            });
        } catch (\Exception $e) {
            return back()->withErrors('Sent failed! ' . $e->getMessage());
        }
        if ($result == null)
            return back()->withSuccess('Sent succeed!');
    }

}

resources/views/editor/post/create.blade.php
@extends('editor.layouts.app', ['include_msg'=>false])
@section('title', 'Writing')
@section('css')
    <link href="//cdn.bootcss.com/select2/4.0.3/css/select2.min.css" rel="stylesheet">
@endsection
@section('content')
    <div id="upload-img-url" data-upload-img-url="{{ route('upload.image') }}" style="display: none"></div>
    <div class="edit-form">
        <img src="{{ isset($post) ? $post->cover_img : old('cover_img') }}" id="cover_img_preview" class="shadow mb-3" style="max-height: 256px;width: 100%;object-fit: cover">
        <form class="form-horizontal" action="{{ route('post.store') }}" method="post">
            @include('editor.post.form-content')
            <button type="submit" class="btn btn-primary">
                {{__('web.CREATE')}}
            </button>
        </form>
    </div>
@endsection

@section('script')
    <script src="//cdn.bootcss.com/select2/4.0.3/js/select2.min.js"></script>
    <script>
        $('#cover_img').change(function () {
            let src = $(this).val();
            $('#cover_img_preview').attr('src', src);
        });
        $("#post-tags").select2({
            tags: true
        });
    </script>
@endsection

resources/views/editor/post/edit.blade.php
@extends('editor.layouts.app')
@section('title', 'Edit ' . $post->title)
@section('css')
    <link href="//cdn.bootcss.com/select2/4.0.3/css/select2.min.css" rel="stylesheet">
@endsection
@section('content')
    <div id="upload-img-url" data-upload-img-url="{{ route('upload.image') }}" style="display: none"></div>
    <div id="data" data-id="{{ $post->id . '.by@' . request()->ip() }}">
        <img src="{{ isset($post) ? $post->cover_img : old('cover_img') }}" id="cover_img_preview" class="shadow mb-3" style="max-height: 256px;width: 100%;object-fit: cover">
        <div class="card-body edit-form">
            <form role="form" class="form-horizontal" action="{{ route('post.update',$post->id) }}"
                  method="post">
                @include('editor.post.form-content')
                <input type="hidden" name="_method" value="put">
                <button type="submit" class="btn btn-primary">
                    {{__('web.EDIT')}}
                </button>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="//cdn.bootcss.com/select2/4.0.3/js/select2.min.js"></script>
    <script>
        $('#cover_img').change(function () {
            let src = $(this).val();
            $('#cover_img_preview').attr('src', src);
        });
        $("#post-tags").select2({
            tags: true
        });
    </script>
@endsection

resources/views/editor/post/form-content.blade.php
<div class="form-group">
    <label for="cover_img" class="form-control-label">{{__('web.COVER_IMAGE')}}</label>
    <input id="cover_img" type="text" class="form-control{{ $errors->has('cover_img') ? ' is-invalid' : '' }}" name="cover_img"
           value="{{ isset($post) ? $post->cover_img : old('cover_img') }}">
    @if ($errors->has('cover_img'))
        <div class="invalid-feedback">
            <strong>{{ $errors->first('cover_img') }}</strong>
        </div>
    @endif
</div>

<div class="form-group">
    <label for="title" class="form-control-label">{{__('web.ARTICLE_TITLE')}}*</label>
    <input id="title" type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title"
           value="{{ isset($post) ? $post->title : old('title') }}"
           autofocus>
    @if ($errors->has('title'))
        <div class="invalid-feedback">
            <strong>{{ $errors->first('title') }}</strong>
        </div>
    @endif
</div>
<div class="form-group">
    <label for="description" class="form-control-label">{{__('web.ARTICLE_DESCRIPTION')}}</label>

    <textarea id="post-description-textarea" style="resize: vertical;" rows="3" spellcheck="false"
              id="description" class="form-control autosize-target{{ $errors->has('description') ? ' is-invalid' : '' }}" placeholder="支持 Markdown 格式"
              name="description">{{ isset($post) ? $post->description : old('description') }}</textarea>

    @if ($errors->has('description'))
        <div class="invalid-feedback">
            <strong>{{ $errors->first('description') }}</strong>
        </div>
    @endif
</div>

<div class="form-group">
    <label for="slug" class="form-control-label">{{__('web.ARTICLE_SLUG')}}*</label>
    <input id="slug" type="text" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}" name="slug"
           value="{{ isset($post) ? $post->slug : old('slug') }}">

    @if ($errors->has('slug'))
        <div class="invalid-feedback">
            <strong>{{ $errors->first('slug') }}</strong>
        </div>
    @endif
</div>

<div class="form-group">
    <label for="categories" class="form-control-label">{{__('web.ARTICLE_CATEGORY')}}*</label>
    <select name="category_id" class="form-control{{ $errors->has('category_id') ? ' is-invalid' : '' }}">
        @foreach($categories as $category)
            @if((isset($post) ? $post->category_id : old('category_id',-1)) == $category->id)
                <option value="{{ $category->id }}" selected>{{ $category->name }}</option>
            @else
                <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endif
        @endforeach
    </select>

    @if ($errors->has('category_id'))
        <div class="invalid-feedback">
            <strong>{{ $errors->first('category_id') }}</strong>
        </div>
    @endif
</div>
<div class="form-group">
    <label for="tags[]" class="form-control-label">{{__('web.ARTICLE_TAGS')}}</label>
    <select style="max-width: 99%" id="post-tags" name="tags[]" class="form-control{{ $errors->has('tags[]') ? ' is-invalid' : '' }}" multiple>
        @foreach($tags as $tag)
            @if(isset($post) && $post->tags->contains($tag))
                <option value="{{ $tag->name }}" selected>{{ $tag->name }}</option>
            @else
                <option value="{{ $tag->name }}">{{ $tag->name }}</option>
            @endif
        @endforeach
    </select>

    @if ($errors->has('tags[]'))
        <div class="invalid-feedback">
            <strong>{{ $errors->first('tags[]') }}</strong>
        </div>
    @endif
</div>
<div class="form-group">
    <label for="post-content-textarea" class="form-control-label">{{__('web.ARTICLE_CONTENT')}}*</label>
    <textarea data-save-id="{{ isset($post)?'post.edit.'.$post->id.'.by@' . request()->ip():'post.create' }}" id="simplemde-textarea"
              class="form-control{{ $errors->has('content') ? ' is-invalid ' : ' ' }}"
              name="content"
              spellcheck="false"
              rows="36"
              placeholder="{{__('web.USE_MARKDOWN_WRITE')}}"
              style="resize: vertical">{{ isset($post) ? $post->content : old('content') }}</textarea>
    @if($errors->has('content'))
        <div class="invalid-feedback">
            <strong>{{ $errors->first('content') }}</strong>
        </div>
    @endif
</div>
<div class="mb-3" style="font-size: 80%">
    <a class="text-secondary font-italic" data-toggle="collapse" href="#post-extra-info" role="button" aria-expanded="false">
        <span title="{{__('web.COMMENT_MESSAGE')}}" data-toggle="tooltip">{{__('web.OTHER_MESSAGE')}}	&raquo;</span>
    </a>
</div>
<div class="collapse" id="post-extra-info">
    <div class="form-group">
        <label for="comment_info" class="form-control-label">{{__('web.OTHER_MESSAGE')}}</label>
        <select style="margin-top: 5px" id="comment_info" name="comment_info" class="form-control">
            <?php $comment_info = isset($post) ? $post->getConfig('comment_info', 'default') : 'default'?>
            <option value="default" {{ $comment_info=='default'?' selected' : '' }}>{{__('web.DEFAULT')}}</option>
            <option value="force_disable" {{ $comment_info=='force_disable'?' selected' : '' }}>{{__('web.FORCE_DISABLE_COMMENT')}}</option>
            <option value="force_enable" {{ $comment_info=='force_enable'?' selected' : '' }}>{{__('web.FORCE_ENABLE_COMMENT')}}</option>
        </select>
    </div>
    <div class="form-group">
        <label for="comment_type" class="form-control-label">{{__('web.COMMENT_TYPE')}}</label>
        <select id="comment_type" name="comment_type" class="form-control">
            <?php $comment_type = isset($post) ? $post->getConfig('comment_type', 'default') : 'default'?>
            <option value="default" {{ $comment_type=='default'?' selected' : '' }}>{{__('web.DEFAULT')}}</option>
            <option value="raw" {{ $comment_type=='raw'?' selected' : '' }}>{{__('web.COMMENT_RAW')}}</option>
            <option value="disqus" {{ $comment_type=='disqus'?' selected' : '' }}>Disqus</option>
        </select>
    </div>

    <div class="form-group">
        <label for="allow_resource_comment" class="form-control-label">{{__('web.ALLOW_RESOURCE_COMMENT')}}</label>
        <select id="allow_resource_comment" name="allow_resource_comment" class="form-control">
            <?php $allow_resource_comment = isset($post) ? $post->getConfig('allow_resource_comment', 'default') : 'default'?>
            <option value="default" {{ $allow_resource_comment=='default'?' selected' : '' }}>{{__('web.DEFAULT')}}</option>
            <option value="false" {{ $allow_resource_comment=='false'?' selected' : '' }}>{{__('web.DISALLOW_COMMENT')}}</option>
            <option value="true" {{ $allow_resource_comment=='true'?' selected' : '' }}>{{__('web.ALLOW_COMMENT')}}</option>
        </select>
    </div>

    <div class="form-group">
        <label for="enable_toc" class="form-control-label">{{__('web.IS_SHOW_TOC')}}</label>
        <select id="enable_toc" name="enable_toc" class="form-control">
            <?php $enable_toc = isset($post) ? $post->getConfig('enable_toc', 'true') : 'true'?>
            <option value="false" {{ $enable_toc=='false'?' selected' : '' }}>{{__('web.CLOSE')}}</option>
            <option value="true" {{ $enable_toc=='true'?' selected' : '' }}>{{__('web.SHOW')}}</option>
        </select>
    </div>
</div>

<div class="form-group">
    <div class="radio radio-inline">
        <label>
            <input type="radio"
                   {{ (isset($post)) && $post->status == 1 ? ' checked ':'' }}
                   name="status"
                   value="1">{{__('web.PUBLISH')}}
        </label>
    </div>
    <div class="radio radio-inline">
        <label>
            <input type="radio"
                   {{ (!isset($post)) || $post->status == 0 ? ' checked ':'' }}
                   name="status"
                   value="0">{{__('web.DRAFT')}}
        </label>
    </div>
</div>
{{ csrf_field() }}